version: '3.8'

services:
  # --- INFRASTRUCTURE SERVICES ---
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/deploy/nginx/sites-available/api:/etc/nginx/conf.d/default.conf
      - /home/deploy/nginx/ssl:/etc/nginx/ssl
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

  api-application:
    image: feerdus95/academia2025-challenge:latest
    networks:
      - app-net
    secrets:
      - postgres_password
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=academia2025_prod
      - DB_USER=postgres
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:15-alpine
    networks:
      - app-net
    secrets:
      - postgres_password
    environment:
      - POSTGRES_DB=academia2025_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # --- MONITORING SERVICES ---
  prometheus:
    image: prom/prometheus:latest
    # NO PORTS - Access through Nginx reverse proxy
    volumes:
      - /home/deploy/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/deploy/monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    # NO PORTS - Access through Nginx reverse proxy
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://mutual-excited-mantis.ngrok-free.app/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_USER}
      - GF_SMTP_FROM_NAME=Novit Monitoring
      - GF_METRICS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
      - /home/deploy/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app-net
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-net
    deploy:
      mode: global

  loki:
    image: grafana/loki:latest
    # NO PORTS - Access through Nginx reverse proxy
    volumes:
      - /home/deploy/monitoring/loki/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /home/deploy/monitoring/loki/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail_positions:/positions
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-net
    deploy:
      mode: global

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    secrets:
      - postgres_password
    volumes:
      - /home/deploy/monitoring/postgres-exporter/queries.yml:/etc/postgres-exporter/queries.yml
    environment:
      - DATA_SOURCE_NAME=postgresql://api_user:$$(cat /run/secrets/postgres_password)@postgres:5432/academia2025_prod?sslmode=disable
    command:
      - --extend.query-path=/etc/postgres-exporter/queries.yml
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

  json-exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - /home/deploy/monitoring/json-exporter/config.yml:/config.json
    command:
      - '--config.file=/config.json'
    networks:
      - app-net
    deploy:
      placement:
        constraints: [node.role == manager]

# --- VOLUMES & NETWORKS ---
volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  loki_data:
  promtail_positions:

networks:
  app-net:
    external: true

secrets:
  postgres_password:
    file: /home/deploy/secrets/postgres_password.txt
